name: NASA Project CI
on:
  push:
    branches:[main]
  pull_request:
    branches:[main]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      -uses: actions/checkout@v2
      -name: using node version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      -run: npm install
      -run: npm run build --prefix client/nasa-front-end